# Generated by Django 5.0.6 on 2024-07-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0002_places'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Places',
            new_name='Place',
        ),
    ]
