# Generated by Django 5.0.6 on 2024-07-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0003_rename_places_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.FloatField(default=1.2838),
        ),
        migrations.AddField(
            model_name='place',
            name='lng',
            field=models.FloatField(default=103.8591),
        ),
    ]
